name: CI with Cache

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: prime-cache-7cfcf29
        id: prime_cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-7cfcf29

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Show cache hit/miss
        run: echo "Cache hit: ${{ steps.prime_cache.outputs.cache-hit }}"
